/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.program3.xgen.view;

import com.program3.xgen.XGen;

/**
 *
 * @author David
 */
public class PanelMedicamento extends javax.swing.JPanel {

    private XGen controlador;

    /**
     * Get the value of controlador
     *
     * @return the value of controlador
     */
    public XGen getControlador() {
        return controlador;
    }

    /**
     * Set the value of controlador
     *
     * @param controlador new value of controlador
     */
    public void setControlador(XGen controlador) {
        this.controlador = controlador;
    }
    
    /**
     * Creates new form NewJPanel
     * @param controlador
     * @param medicameto
     */
    public PanelMedicamento(XGen controlador, Object medicameto) {
        this.controlador=controlador;
        initComponents();
    }
    /**
     * Creates new form NewJPanel
     * @param controlador
     */
    public PanelMedicamento(XGen controlador) {
        this.controlador=controlador;
        initComponents();
    }
    /**
     * Creates new form NewJPanel
     */
    public PanelMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medicamento");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
