/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.program3.xgen.view;

import java.util.GregorianCalendar;

import com.program3.xgen.XGen;
import com.program3.xgen.model.Medicamento;

/**
 *
 * @author David
 * @param <t>
 */
public class PanelMedicamentoMostrar<t extends Medicamento> extends javax.swing.JPanel {

    private XGen controlador;

    /**
     * Get the value of controlador
     *
     * @return the value of controlador
     */
    public XGen getControlador() {
        return controlador;
    }

    /**
     * Set the value of controlador
     *
     * @param controlador new value of controlador
     */
    public void setControlador(XGen controlador) {
        this.controlador = controlador;
    }
    
    /**
     * Creates new form NewJPanel

     * @param controlador
     * @param nuevoMedicamento
     */
    public PanelMedicamentoMostrar(XGen controlador, t nuevoMedicamento) {
        this.controlador=controlador;
        this.medicamento = nuevoMedicamento;
        initComponents();
        java.awt.Rectangle r = this.jPanel4.getBounds();
        if(nuevoMedicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado){
            this.jPanel2.setBounds((int)r.getX(), (int)r.getY(), 0, 0);
        }else{
            this.jPanel3.setBounds((int)r.getX(), (int)r.getY(), 0, 0);
        }
    }
    /**
     * Creates new form NewJPanel
     * @param controlador
     */
    public PanelMedicamentoMostrar(XGen controlador) {
        this.controlador=controlador;
        initComponents();
    }
    /**
     * Creates new form NewJPanel
     */
    public PanelMedicamentoMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vigencia = new javax.swing.JComboBox<>();
        unidadesVendidas = new javax.swing.JFormattedTextField();
        numeroDeLote = new javax.swing.JFormattedTextField();
        existencia = new javax.swing.JFormattedTextField();
        porcentajeGanancia = new javax.swing.JFormattedTextField();
        costeMedicamento = new javax.swing.JFormattedTextField();
        codigoMedicamento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fechaCaducidad = new javax.swing.JSpinner();
        nombreMedicamento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        noGuardar1 = new javax.swing.JTextField();
        noGuardar2 = new javax.swing.JTextField();
        noGuardar3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        temperaturaMaxima = new javax.swing.JSpinner();
        temperaturaMinima = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        almacenamiento = new javax.swing.JTextField();
        expoLuz = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        expoHumedad = new javax.swing.JTextField();
        transporte = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        durabilidadLuegoDeAbierto = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medicamento");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel3.setText("Codigo");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Coste");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setText("Porcentaje de Ganancia");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setText("Existencia");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setText("Unidades vendidas");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel8.setText("Número de Lote");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel9.setText("Vigencia");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel10.setText("Nombre");

        vigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0. No está Disponible", "1. Está Disponible", "2. Fue retirado del mercado" }));
        vigencia.getModel().setSelectedItem(medicamento.getVigencia());
        vigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenciaActionPerformed(evt);
            }
        });

        unidadesVendidas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        unidadesVendidas.setText(Integer.toString(this.medicamento.getUnidadesVendidas()));
        unidadesVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadesVendidasActionPerformed(evt);
            }
        });

        numeroDeLote.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numeroDeLote.setText(Integer.toString(this.medicamento.getNumeroLote()));
        numeroDeLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeLoteActionPerformed(evt);
            }
        });

        existencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        existencia.setText(Integer.toString(this.medicamento.getExistencia()));
        existencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existenciaActionPerformed(evt);
            }
        });

        porcentajeGanancia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        porcentajeGanancia.setText(Double.toString(this.medicamento.getPorcentajeDeGanancia()));
        porcentajeGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeGananciaActionPerformed(evt);
            }
        });

        costeMedicamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        costeMedicamento.setText(Double.toString(this.medicamento.getCosteProduccion()));
        costeMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costeMedicamentoActionPerformed(evt);
            }
        });

        codigoMedicamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        codigoMedicamento.setText(Integer.toString(this.medicamento.getCodigoMedicamento()));
        codigoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMedicamentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio");

        precio.setBackground(java.awt.SystemColor.window);
        precio.setText(Double.toString(medicamento.getPrecio()));
        precio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setText("Caducidad");

        fechaCaducidad.setModel(new javax.swing.SpinnerDateModel(medicamento.getCaducidad().getTime(), medicamento.getCaducidad().getTime(), null, java.util.Calendar.DAY_OF_MONTH));

        nombreMedicamento.setText(this.medicamento.getNombreMedicamento());
        nombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(numeroDeLote, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(124, 124, 124)
                        .addComponent(costeMedicamento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vigencia, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                            .addComponent(existencia)
                            .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(porcentajeGanancia)
                            .addComponent(unidadesVendidas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMedicamento)
                            .addComponent(codigoMedicamento))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreMedicamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(codigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(costeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(porcentajeGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(existencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadesVendidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numeroDeLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(fechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        fechaCaducidad.getAccessibleContext().setAccessibleName("");
        fechaCaducidad.getModel().getValue();

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 0));

        jLabel12.setText("Indique por lo menos  3 lugares donde no se ");

        jLabel22.setText("debe almacenar este medicamento:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        noGuardar1.setText("jTextField6");
        if (medicamento instanceof com.program3.xgen.model.MedicamentoAmbiente medicamento){
            noGuardar1.setText(medicamento.getCondicionesAlmacenamiento()[0]);
        }
        jPanel5.add(noGuardar1);

        noGuardar2.setText("jTextField7");
        if (medicamento instanceof com.program3.xgen.model.MedicamentoAmbiente medicamento){
            noGuardar2.setText(medicamento.getCondicionesAlmacenamiento()[1]);
        }
        jPanel5.add(noGuardar2);

        noGuardar3.setText("jTextField8");
        if (medicamento instanceof com.program3.xgen.model.MedicamentoAmbiente medicamento){
            noGuardar3.setText(medicamento.getCondicionesAlmacenamiento()[2]);
        }
        jPanel5.add(noGuardar3);

        jScrollPane1.setViewportView(jPanel5);

        jButton3.setText("Añadir más campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel22)
                    .addComponent(jLabel12))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        if(medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado){
            this.jPanel2.setVisible(false);
        }
        add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel18.setText("Temperatura Mínima");

        jLabel19.setText("Temperatura Máxima");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            temperaturaMaxima.setModel(new javax.swing.SpinnerNumberModel(medicamento.getTemperaturaMaxima(), -272, 15, 1));
        }

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            temperaturaMinima.setModel(new javax.swing.SpinnerNumberModel(medicamento.getTemperaturaMinima(), -273, 15, 1));
        }

        jLabel25.setText("almacenamiento");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            almacenamiento.setText((medicamento.getInformacionCadenaDeFrio())[0]);}
        almacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenamientoActionPerformed(evt);
            }
        });

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            expoLuz.setText((medicamento.getInformacionCadenaDeFrio())[1]);}
        expoLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expoLuzActionPerformed(evt);
            }
        });

        jLabel26.setText("Exposición a la luz");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel27.setText("transporte");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel28.setText("Exposición a la Humedad");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            expoHumedad.setText((medicamento.getInformacionCadenaDeFrio())[2]);}
        expoHumedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expoHumedadActionPerformed(evt);
            }
        });

        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            transporte.setText((medicamento.getInformacionCadenaDeFrio())[3]);}
        transporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transporteActionPerformed(evt);
            }
        });

        jLabel21.setText("Durabilidad después de abierto");

        durabilidadLuegoDeAbierto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        if (medicamento instanceof com.program3.xgen.model.MedicamentoRefrigerado medicamento){
            durabilidadLuegoDeAbierto.setText(Integer.toString(medicamento.getDurabilidadLuegoDeAbierto()));
        }

        jLabel11.setText("(semanas)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(79, 79, 79)
                                .addComponent(temperaturaMinima, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(77, 77, 77)
                                .addComponent(temperaturaMaxima))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(expoLuz, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(almacenamiento)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transporte, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(expoHumedad)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(durabilidadLuegoDeAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(temperaturaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(temperaturaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(durabilidadLuegoDeAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(expoLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(expoHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        if(medicamento instanceof com.program3.xgen.model.MedicamentoAmbiente){
            this.jPanel3.setVisible(false);
        }
        add(jPanel3, java.awt.BorderLayout.WEST);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        add(jPanel4, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void vigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigenciaActionPerformed

    private void unidadesVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadesVendidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadesVendidasActionPerformed

    private void numeroDeLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDeLoteActionPerformed

    private void existenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existenciaActionPerformed

    private void porcentajeGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeGananciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeGananciaActionPerformed

    private void costeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costeMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costeMedicamentoActionPerformed

    private void codigoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMedicamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.cerrarPanelEditar((javax.swing.JTabbedPane)this.getParent(), this);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicamentoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        javax.swing.JTextField nuevo = new javax.swing.JTextField();
        jPanel5.add(nuevo);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void transporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transporteActionPerformed

    private void expoHumedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expoHumedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expoHumedadActionPerformed

    private void expoLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expoLuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expoLuzActionPerformed

    private void almacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenamientoActionPerformed

    private t medicamento;

    /**
     * Get the value of medicamento
     *
     * @return the value of medicamento
     */
    public t getMedicamento() {
        return medicamento;
    }

    /**
     * Set the value of medicamento
     *
     * @param medicamento new value of medicamento
     */
    public void setMedicamento(t medicamento) {
        this.medicamento = medicamento;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almacenamiento;
    private javax.swing.JFormattedTextField codigoMedicamento;
    private javax.swing.JFormattedTextField costeMedicamento;
    private javax.swing.JFormattedTextField durabilidadLuegoDeAbierto;
    private javax.swing.JFormattedTextField existencia;
    private javax.swing.JTextField expoHumedad;
    private javax.swing.JTextField expoLuz;
    private javax.swing.JSpinner fechaCaducidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noGuardar1;
    private javax.swing.JTextField noGuardar2;
    private javax.swing.JTextField noGuardar3;
    private javax.swing.JTextField nombreMedicamento;
    private javax.swing.JFormattedTextField numeroDeLote;
    private javax.swing.JFormattedTextField porcentajeGanancia;
    private javax.swing.JLabel precio;
    private javax.swing.JSpinner temperaturaMaxima;
    private javax.swing.JSpinner temperaturaMinima;
    private javax.swing.JTextField transporte;
    private javax.swing.JFormattedTextField unidadesVendidas;
    private javax.swing.JComboBox<String> vigencia;
    // End of variables declaration//GEN-END:variables
}
